# ---------------- #
#   Main Configs   #
# ---------------- #
# baseurl:
date_format: "ordinal"
title: 碎雪的小屋
subtitle: "<script>alert("xss")</script>"
description: "有很多未完成的坑，我会慢慢填的（逃"
keywords: Roy, 碎雪, 信息安全, 
favicon: /favicon.ico
timezone: Asia/Chongqing
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Su1_Xu3
organization: 碎雪的小屋
organization_url: https://roytse.github.io/
github_username: RoyTse
location: ChongQing, China
email: 907064516@qq.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: RoyTse/RoyTse.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: Su1_Xu3
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: RoyTse
    repo: blog-comments
    oauth:
        client_id: 7c5c889ae891f04444c2
        client_secret: adf5918ec01b4f0c4733a8a041d5c4fa8b559d54
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: RoyTse
    repo: blog-comments
    clientID: 7c5c889ae891f04444c2
    clientSecret: adf5918ec01b4f0c4733a8a041d5c4fa8b559d54
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : true

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1
